_target_: calvin_env.scene.play_table_scene.PlayTableScene
_recursive_: false
data_path: ${data_path}
global_scaling: 0.8
euler_obs: ${robot.euler_obs}
robot_base_position: [-0.34, -0.46, 0.24]
robot_base_orientation: [0, 0, 0]
robot_initial_joint_positions: [-1.21779206,  1.03987646,  2.11978261, -2.34205014, -0.87015947, 1.64119353,  0.55344866]
surfaces:
  table_top: [[0.0, -0.15, 0.46], [0.35, -0.03, 0.46]]
  drawer: [[0.0, -0.3, 0.46], [0.35, -0.18, 0.46]]
  # slider_left: [[-0.32, 0.05, 0.46], [-0.16, 0.12, 0.46]]
  # slider_right: [[-0.05, 0.05, 0.46], [0.13, 0.12, 0.46]]
objects:
  fixed_objects:
    table:
      file: calvin_table_D/urdf/calvin_table_D.urdf
      initial_pos: [0, 0, 0]
      initial_orn: [0, 0, 0]
      joints:
        base__slide:
          initial_state: 0 # Prismatic
        base__drawer:
          initial_state: 0.23 # Prismatic
      buttons: {}
      switches: {}
      lights: {}
  movable_objects:
    block_red:
      file: blocks/block_red_middle.urdf
      initial_pos: any
      initial_orn: any
